//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionAngela.EFRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdministracionAngelaContext : DbContext
    {
        public AdministracionAngelaContext()
            : base("name=AdministracionAngelaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IVA> IVA { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<LineaFactura> LineaFactura { get; set; }
        public virtual DbSet<LineaAlbaran> LineaAlbaran { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Albaran> Albaran { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
