//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionAngela.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaAlbaran
    {
        public long Id { get; set; }
        public long NumeroAlbaran { get; set; }
        public bool IsAlbaran { get; set; }
        public long ProductoId { get; set; }
        public decimal PorcentajeIVA { get; set; }
        public Nullable<decimal> PorcentajeRE { get; set; }
        public Nullable<decimal> Kgs { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Cajas { get; set; }
        public string FAO { get; set; }
        public string ZonaCaptura { get; set; }
        public string NombreCientifico { get; set; }
        public string ArtePesca { get; set; }
        public string Lote { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> ImporteIVA { get; set; }
        public Nullable<decimal> ImporteRE { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Albaran Albaran { get; set; }
    }
}
