//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionAngela.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaFactura
    {
        public long Id { get; set; }
        public long NumeroFactura { get; set; }
        public long ProductoId { get; set; }
        public int IVAId { get; set; }
        public Nullable<int> Unidades { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual IVA IVA { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
