//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionAngela.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaAlbaran
    {
        public long Id { get; set; }
        public long AlbaranId { get; set; }
        public long ProductoId { get; set; }
        public decimal PorcentajeIVA { get; set; }
        public Nullable<decimal> PorcentajeRE { get; set; }
        public Nullable<decimal> Kgs { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Cajas { get; set; }
        public string FAO { get; set; }
        public string ZonaCaptura { get; set; }
        public string NombreCientifico { get; set; }
        public string ArtePesca { get; set; }
        public string Lote { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> ImporteIVA { get; set; }
        public Nullable<decimal> ImporteRE { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Albaran Albaran { get; set; }
    }
}
