//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionAngela.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string NIF { get; set; }
        public string CIF { get; set; }
        public Nullable<int> DireccionId { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public string Iban { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Contacto Contacto { get; set; }
    }
}
