//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionAngela.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.LineaAlbaran = new HashSet<LineaAlbaran>();
            this.LineaFactura = new HashSet<LineaFactura>();
        }
    
        public long Id { get; set; }
        public int CodigoProducto { get; set; }
        public int IVAId { get; set; }
        public string Descripcion { get; set; }
        public string NombreCientifico { get; set; }
        public string FAO { get; set; }
        public string ArtePesca { get; set; }
        public string ZonaCaptura { get; set; }
        public string Abreviacion { get; set; }
    
        public virtual IVA IVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaAlbaran> LineaAlbaran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaFactura> LineaFactura { get; set; }
    }
}
