//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionAngela.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.LineaFactura = new HashSet<LineaFactura>();
            this.LineaAlbaran = new HashSet<LineaAlbaran>();
        }
    
        public long Id { get; set; }
        public int CodigoProducto { get; set; }
        public int IVAId { get; set; }
        public string Descripcion { get; set; }
        public string NombreCientifico { get; set; }
        public string FAO { get; set; }
        public string ArtePesca { get; set; }
        public string ZonaCaptura { get; set; }
        public string Abreviacion { get; set; }
    
        public virtual IVA IVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaFactura> LineaFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaAlbaran> LineaAlbaran { get; set; }
    }
}
